# Generated by Django 2.2.20 on 2021-04-20 13:18

import uuid

import django_extensions.db.fields
from django.db import migrations, models

import users.models.users


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UnikubeUser",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "avatar_image",
                    models.FileField(
                        blank=True, default=users.models.users.get_default_avatar_image, null=True, upload_to=""
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
